#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Migrating"
python manage.py migrate_schemas

echo "INIT Data"
python manage.py runscript initialise

exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
